api_platform:
    title: CheckPoint - API
    description: API pour mon site  appelée CheckPoint
    version: 1.0.0
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']