lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_PRIVATE_KEY_PATH)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # 1 heure
    clock_skew: 0
    allow_no_expiration: false
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: BEARER
    set_cookies:
        BEARER:
            lifetime: 3600
            path: /
            domain: null
            secure: true
            httpOnly: true
            samesite: 'lax'
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: password
